### PR TITLE
add margin-right to checkbox

### PR DESCRIPTION
**Pull request by episodeyang**

### CODE REVIEW

**Comment by sindresorhus** [comment]
This CSS is automagically generated. https://github.com/sindresorhus/generate-github-markdown-css

**Comment by episodeyang** [comment]
whoops
shall I head there then?

**Comment by episodeyang** [comment]
Okay I think I understand now. Why is it different from what we see on GitHub then? a bit confused...

**Comment by episodeyang** [comment]
okay I found the reason. Thanks!

**Pull request closed without merging**
