### PR TITLE
fix: don't break words in table

### PR DESCRIPTION
**Pull request by gcusnieux**
Hi, 

I update from 4.0.0 and I have some display problems with tables.

**With 4.0.0**
Capture d’écran 2021-12-21 à 08 52 39

**With 5.1.0**
Capture d’écran 2021-12-21 à 08 52 09

**On github:**
https://github.com/gravitee-io/gravitee-policy-mock
Capture d’écran 2021-12-21 à 09 22 16

**With the fix**

Capture d’écran 2021-12-21 à 09 21 18

### CODE REVIEW

**Comment by hyrious** [comment]
GitHub doesn't apply `whitespace: nowrap` to table elements. Can you please look into it to see why your table gets short width?

**Comment by gcusnieux** [comment]
Yes, it's true. But I don't find why table content not break space

**Comment by sindresorhus** [comment]
Per the readme, the CSS is generated. You have to fix it at the source.

**Comment by gcusnieux** [comment]
> Per the readme, the CSS is generated. You have to fix it at the source.

I don't understand how to fix the README.
If with the same README the render is not the same on Github, it's a bug no ?

**Comment by sindresorhus** [comment]
@gcusnieux Read my comment again. I'm not saying the bug is invalid, I'm saying the fix is.

**Comment by gcusnieux** [comment]
No worries, when I read I understand that's fix should be provide by README

**Pull request closed without merging**
